project: default
source:
  repoURL: https://github.com/cremerica/k8s-flask.git
  path: chart
  targetRevision: HEAD
  helm:
    valueFiles:
      - values.yaml
    parameters:
      - name: commitHash
        value: $ARGOCD_APP_REVISION
      - name: argoRepo
        value: $ARGOCD_APP_SOURCE_REPO_URL
destination:
  server: https://34.68.88.89
  namespace: k8s-flask-helm
