apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-flask
  labels:
    backstage.io/kubernetes-id: k8s-flask
  annotations:
    link.argocd.argoproj.io/external-link: https://app.komodor.com/services/cremerica.desktop-appdirect.k8s-flask
    'backstage.io/kubernetes-id': k8s-flask
    app.komodor.com/app: https://github.com/cremerica/k8s-flask
    app.komodor.com/app.ref: ${ARGOCD_APP_REVISION}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-flask
  template:
    metadata:
      labels:
        app: k8s-flask
        backstage.io/kubernetes-id: k8s-flask
      annotations:
        'backstage.io/kubernetes-id': k8s-flask
    spec:
      containers:
      - name: flask-container
        image: cremerfc/k8s-flask:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
        volumeMounts:
        - name: flask-data
          mountPath: /data
      volumes:
      - name: flask-data
        persistentVolumeClaim:
          claimName: k8s-flask-pvc
