apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaky-app
  annotations:
    'backstage.io/kubernetes-id': k8s-flask
  labels:
    backstage.io/kubernetes-id: k8s-flask  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-flask
  template:
    metadata:
      labels:
        app: k8s-flask
    spec:
      containers:
      - name: flask-container
        image: cremerfc/k8s-flaskw:latest
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
